# Generated by Django 4.0.1 on 2022-01-26 10:18

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('documentary', 'Documentary'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('crime', 'Crime'), ('sci-fi', 'Sci-Fi')], default=1, max_length=20)),
                ('rating', models.IntegerField()),
                ('type', models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], default=1, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flyer', models.ImageField(upload_to=movies.models.upload_to)),
                ('age_limit', models.CharField(choices=[('all', 'All'), ('kids', 'Kids')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=500)),
                ('videofile', models.FileField(upload_to='movies')),
                ('movie', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
