# Generated by Django 4.0.1 on 2022-01-26 10:20

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=models.ImageField(default='GOT.jfif', upload_to=movies.models.upload_to),
        ),
    ]
