# Generated by Django 4.0.1 on 2022-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(default='video1.mp4', upload_to='movies'),
        ),
    ]
