# Generated by Django 4.0.1 on 2022-02-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_video_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isNetflixOriginals',
            field=models.BooleanField(default=False),
        ),
    ]
